[2023-03-30T01:05:47.843+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: audio_processing_dag.transcribe_audio manual__2023-03-30T01:05:45.281534+00:00 [queued]>
[2023-03-30T01:05:47.849+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: audio_processing_dag.transcribe_audio manual__2023-03-30T01:05:45.281534+00:00 [queued]>
[2023-03-30T01:05:47.849+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T01:05:47.850+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-30T01:05:47.850+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T01:05:47.857+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): transcribe_audio> on 2023-03-30 01:05:45.281534+00:00
[2023-03-30T01:05:47.862+0000] {standard_task_runner.py:55} INFO - Started process 792 to run task
[2023-03-30T01:05:47.866+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'audio_processing_dag', 'transcribe_audio', 'manual__2023-03-30T01:05:45.281534+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/adhoc.py', '--cfg-path', '/tmp/tmpa56ulkww']
[2023-03-30T01:05:47.869+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask transcribe_audio
[2023-03-30T01:05:47.921+0000] {task_command.py:388} INFO - Running <TaskInstance: audio_processing_dag.transcribe_audio manual__2023-03-30T01:05:45.281534+00:00 [running]> on host 1ae242592484
[2023-03-30T01:05:47.966+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=audio_processing_dag
AIRFLOW_CTX_TASK_ID=transcribe_audio
AIRFLOW_CTX_EXECUTION_DATE=2023-03-30T01:05:45.281534+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-30T01:05:45.281534+00:00
[2023-03-30T01:05:47.978+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/adhoc.py", line 61, in transcribe_audio
    context['task_instance'].xcom_push(key='transcription', value=transcription)
UnboundLocalError: local variable 'transcription' referenced before assignment
[2023-03-30T01:05:47.987+0000] {taskinstance.py:1321} INFO - Marking task as UP_FOR_RETRY. dag_id=audio_processing_dag, task_id=transcribe_audio, execution_date=20230330T010545, start_date=20230330T010547, end_date=20230330T010547
[2023-03-30T01:05:47.994+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 82 for task transcribe_audio (local variable 'transcription' referenced before assignment; 792)
[2023-03-30T01:05:48.039+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-30T01:05:48.061+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
